version: '3.8'
services:
  script_runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: python:3.9-slim
    command: tail -f /dev/null
    volumes:
      - ./data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
